<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-19T00:24:23Z" name="Default suite" finished-at="2021-05-19T00:24:24Z" duration-ms="1062">
    <groups>
    </groups>
    <test started-at="2021-05-19T00:24:23Z" name="Default test" finished-at="2021-05-19T00:24:24Z" duration-ms="1062">
      <class name="extentRepoetsTutorial.ExtentReportTestNG">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:extentRepoetsTutorial.ExtentReportTestNG@ca30bc1]" started-at="2021-05-19T00:24:23Z" name="beforeSuite" finished-at="2021-05-19T00:24:23Z" duration-ms="606" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method signature="interntionalFailure()[pri:0, instance:extentRepoetsTutorial.ExtentReportTestNG@ca30bc1]" started-at="2021-05-19T00:24:23Z" name="interntionalFailure" finished-at="2021-05-19T00:24:23Z" duration-ms="17" status="FAIL">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Intentional Failure successfull!!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Intentional Failure successfull!!!
at extentRepoetsTutorial.ExtentReportTestNG.interntionalFailure(ExtentReportTestNG.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- interntionalFailure -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:extentRepoetsTutorial.ExtentReportTestNG@ca30bc1]" started-at="2021-05-19T00:24:23Z" name="afterMethod" finished-at="2021-05-19T00:24:24Z" duration-ms="794" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=interntionalFailure status=FAILURE method=ExtentReportTestNG.interntionalFailure()[pri:0, instance:extentRepoetsTutorial.ExtentReportTestNG@ca30bc1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="passTest()[pri:0, instance:extentRepoetsTutorial.ExtentReportTestNG@ca30bc1]" started-at="2021-05-19T00:24:24Z" name="passTest" finished-at="2021-05-19T00:24:24Z" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passTest -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:extentRepoetsTutorial.ExtentReportTestNG@ca30bc1]" started-at="2021-05-19T00:24:24Z" name="afterMethod" finished-at="2021-05-19T00:24:24Z" duration-ms="195" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=passTest status=SUCCESS method=ExtentReportTestNG.passTest()[pri:0, instance:extentRepoetsTutorial.ExtentReportTestNG@ca30bc1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:extentRepoetsTutorial.ExtentReportTestNG@ca30bc1]" started-at="2021-05-19T00:24:24Z" name="afterSuite" finished-at="2021-05-19T00:24:25Z" duration-ms="92" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- extentRepoetsTutorial.ExtentReportTestNG -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
