<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-08-30T21:54:58Z" name="Default suite" finished-at="2019-08-30T21:55:00Z" duration-ms="1632">
    <groups>
    </groups>
    <test started-at="2019-08-30T21:54:58Z" name="Default test" finished-at="2019-08-30T21:55:00Z" duration-ms="1632">
      <class name="ententReportv4.ExtentReportPractice">
        <test-method is-config="true" signature="startReport()[pri:0, instance:ententReportv4.ExtentReportPractice@fdefd3f]" started-at="2019-08-30T21:54:58Z" name="startReport" finished-at="2019-08-30T21:54:58Z" duration-ms="370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method signature="demoReportFail()[pri:0, instance:ententReportv4.ExtentReportPractice@fdefd3f]" started-at="2019-08-30T21:54:58Z" name="demoReportFail" finished-at="2019-08-30T21:54:58Z" duration-ms="24" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at ententReportv4.ExtentReportPractice.demoReportFail(ExtentReportPractice.java:46)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportFail -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:ententReportv4.ExtentReportPractice@fdefd3f]" started-at="2019-08-30T21:54:58Z" name="getResult" finished-at="2019-08-30T21:54:58Z" duration-ms="20" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportFail status=FAILURE method=ExtentReportPractice.demoReportFail()[pri:0, instance:ententReportv4.ExtentReportPractice@fdefd3f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method signature="demoReportPass()[pri:0, instance:ententReportv4.ExtentReportPractice@fdefd3f]" started-at="2019-08-30T21:54:58Z" name="demoReportPass" finished-at="2019-08-30T21:54:58Z" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- demoReportPass -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:ententReportv4.ExtentReportPractice@fdefd3f]" started-at="2019-08-30T21:54:58Z" name="getResult" finished-at="2019-08-30T21:54:58Z" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=demoReportPass status=SUCCESS method=ExtentReportPractice.demoReportPass()[pri:0, instance:ententReportv4.ExtentReportPractice@fdefd3f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:ententReportv4.ExtentReportPractice@fdefd3f]" started-at="2019-08-30T21:54:58Z" name="endReport" finished-at="2019-08-30T21:55:00Z" duration-ms="1137" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- ententReportv4.ExtentReportPractice -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
